name: Mirror

on:
  push:
    branches: [main, master]
    tags: ['*']

jobs:
  gitlab:
    uses: MoritzThome/ALF/.github/workflows/mirror-template.yml@master
    if: github.repository == 'AMF-QMC/ALF'
    with:
      git_url: "git.physik.uni-wuerzburg.de/mthome/ALF"
    secrets:
      GIT_MIRROR_TOKEN: ${{ secrets.GITLAB_MIRROR_TOKEN }}
